version: "3.9"
services:
  golem:
    platform: linux/x86_64
    container_name: golem
    image: golem-bot
    build:
      context: $PWD
      dockerfile: $PWD/docker/Dockerfile
    ports:
      - "3828:3828"
    depends_on:
      - mongo
    command: ['npm', 'run', 'build']
    volumes: 
      - $PWD:/opt/golem
  mongo:
    container_name: golem-mongo
    image: mongo
